Repository huamanraj/Covid_website, pull requests merged in 2023-10, with the labels that each got.

#15 feature/Improving the repo architecture
  index.html
  login_signup_page/Login.html
  pages/auth/Login.html
  pages/auth/SignUp.html
  pages/contact.html
  static/css/auth.css
  static/css/contact.css
  static/css/style.css
  static/images/favicon.png
  static/images/fb.svg
  static/images/ig.png
  static/images/sect-1.jpg
  static/images/sect-2.jpg
  static/images/sect-3.png
  static/images/symptoms.jpg
  static/images/twitter.svg
  static/images/yt.svg
Labels: hacktoberfest-accepted

#27 changed text from lorem Ipsum to about covid
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#35 improved the about us section
  index.html
  static/css/style.css
Labels: hacktoberfest-accepted

#36 improved footer and formatted the code.
  index.html
  static/css/auth.css
  static/css/contact.css
  static/css/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#40 successfully created navbar
  index.html
  static/css/style.css
  static/images/coronavirus.svg
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#39 adding symptoms.html file with beautiful design
  static/css/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#42 Implemented CSS on coronovirus Statistics
  index.html
  static/css/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#48 Improved Section-How To Protect Yourself
  index.html
  static/css/style.css
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#50 improving hero section
  index.html
  static/css/style.css
Labels: hacktoberfest-accepted
